services:
  nginx:
    image: nginx:latest
    container_name: elektron-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  backend:
    image: nishanpaudel/elektron-backend
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" , "--reload", ]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb+srv://cmpe-272:cmpe-272@cluster0.crznvzq.mongodb.net/elektron?retryWrites=true&w=majority&appName=Cluster0
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - MAILJET_API_KEY="70fd675f4b25b68b6d6ce5393d83b54e"
      - MAILJET_SECRET_KEY="4d6fea1b4164858bdc1f2a3fe9908752"
      - MAILJET_SENDER_EMAIL="noreplybooktable@gmail.com"



  frontend:
    image: nishanpaudel/elektron-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://18.215.147.51/api
    depends_on:
      - backend


