services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/elektron?authSource=admin
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    depends_on:
      - kafka  #   Ensure Kafka starts before backend
      - mongo

  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: [ "bash", "scheduler/run_scripts.sh" ]
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/elektron?authSource=admin
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    depends_on:
      - kafka  #   Ensure Kafka starts before backend


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend


  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"

  mongo:
    image: mongo:6.0
    container_name: mongo-elektron
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express-elektron
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo


volumes:
  mongodb_data:
