version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.21
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
    restart: always
    networks:
      - elektron_net

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=123456
      - DOCKER_INFLUXDB_INIT_ORG=elektron_org
      - DOCKER_INFLUXDB_INIT_BUCKET=electricity_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=123456
    restart: always
    networks:
      - elektron_net

  grafana:
    image: grafana/grafana-oss:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_ADMIN_USER=admin
      - GF_AUTH_ADMIN_PASSWORD=123456
    restart: always
    depends_on:
      - influxdb
    networks:
      - elektron_net

volumes:
  mosquitto_config:
  mosquitto_data:
  influxdb_data:
  grafana_data:

networks:
  elektron_net:
    driver: bridge


