services:
  nginx:
    image: nginx:latest
    container_name: elektron-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  backend:
    image: nishanpaudel/elektron-backend
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" , "--workers", "2" ]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb+srv://cmpe-272:cmpe-272@cluster0.crznvzq.mongodb.net/elektron?retryWrites=true&w=majority&appName=Cluster0
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092



  frontend:
    image: nishanpaudel/elektron-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://18.215.147.51/api
    depends_on:
      - backend
      - nginx


