name: Build, Push Docker Images, and Deploy to EC2

on:
  push:
    branches: [ "working" ]
  pull_request:
    branches: [ "working" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/elektron-backend:latest

    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/elektron-frontend:latest


#    - name: Deploy to EC2
#      uses: appleboy/ssh-action@v0.1.10
#      with:
#        host: ${{ secrets.EC2_HOST }}
#        username: ${{ secrets.EC2_USERNAME }}
#        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
#        script: |
#          cd ~
#          if [ ! -d "elektron" ]; then
#            git clone https://github.com/nishan7/elektron.git
#          fi
#          cd Bridge-Work
#          git pull origin main
#          docker-compose -f docker-compose.prod.yml pull
#          docker-compose -f docker-compose.prod.yml up backend frontend kafka -d --remove-orphans
